// <auto-generated />
using System;
using MeuCash.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeuCash.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(MeuCashDbContext))]
    [Migration("20260516015513_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeuCash.Core.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("tab_Categoria", (string)null);
                });

            modelBuilder.Entity("MeuCash.Core.Entidades.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("tab_Conta", (string)null);
                });

            modelBuilder.Entity("MeuCash.Core.Entidades.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdConta")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdConta");

                    b.ToTable("tab_Despesa", (string)null);
                });

            modelBuilder.Entity("MeuCash.Core.Entidades.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<int>("IdConta")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.ToTable("tab_Entrada", (string)null);
                });

            modelBuilder.Entity("MeuCash.Core.Entidades.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataLimite")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<int>("IdConta")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdConta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("tab_Meta", (string)null);
                });

            modelBuilder.Entity("MeuCash.Core.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("NumeroCelular")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(24)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(80)");

                    b.HasKey("Id");

                    b.ToTable("tab_Usuarios", (string)null);
                });

            modelBuilder.Entity("MeuCash.Core.Entidades.Conta", b =>
                {
                    b.HasOne("MeuCash.Core.Entidades.Usuario", "UsuarioConta")
                        .WithOne("Conta")
                        .HasForeignKey("MeuCash.Core.Entidades.Conta", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioConta");
                });

            modelBuilder.Entity("MeuCash.Core.Entidades.Despesa", b =>
                {
                    b.HasOne("MeuCash.Core.Entidades.Categoria", "Categoria")
                        .WithMany("Despesas")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeuCash.Core.Entidades.Conta", "Conta")
                        .WithMany("Despesas")
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("MeuCash.Core.Entidades.Entrada", b =>
                {
                    b.HasOne("MeuCash.Core.Entidades.Conta", "Conta")
                        .WithMany("Entradas")
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("MeuCash.Core.Entidades.Meta", b =>
                {
                    b.HasOne("MeuCash.Core.Entidades.Conta", "Conta")
                        .WithMany("Metas")
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeuCash.Core.Entidades.Usuario", "Usuario")
                        .WithMany("Metas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MeuCash.Core.Entidades.Categoria", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("MeuCash.Core.Entidades.Conta", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Entradas");

                    b.Navigation("Metas");
                });

            modelBuilder.Entity("MeuCash.Core.Entidades.Usuario", b =>
                {
                    b.Navigation("Conta")
                        .IsRequired();

                    b.Navigation("Metas");
                });
#pragma warning restore 612, 618
        }
    }
}
